/** Real BA/SA terms shown first in every article. */
export const TERMS = {
  "req-need": {
    name: "Требование",
    en: "requirement",
    def: "Проверяемое правило поведения системы: если случилось A, система делает B — и это видно на экране или в данных.",
  },
  "req-story": {
    name: "User Story",
    en: "user story",
    name2: "Use Case",
    en2: "use case",
    def: "User Story — кто, что хочет и зачем в работе. Use Case — шаги сценария, включая ошибки и повтор.",
  },
  "req-levels": {
    name: "Уровни требований",
    en: "requirement levels",
    def: "Четыре слоя одного изменения: бизнес-цель, стейкхолдер, системное правило, критерий проверки.",
  },
  "req-ac": {
    name: "Acceptance Criteria",
    en: "acceptance criteria",
    def: "Критерии приёмки: наблюдаемые условия, при которых требование считается выполненным. Часто в форме Given / When / Then.",
  },
  "req-brd": {
    name: "BRD",
    en: "business requirements document",
    def: "Документ бизнес-требований: зачем организация меняется, какие цели и ограничения — не список экранов.",
  },
  "req-nfr": {
    name: "NFR",
    en: "non-functional requirements",
    def: "Нефункциональные требования: как система должна себя вести по объёму, времени, безопасности, доступности — не «удобно».",
  },
  "req-trace": {
    name: "Трассировка",
    en: "requirements traceability",
    def: "Связь need → требование → реализация → тест. Если звено вырезали — дыра видна.",
  },
  "req-stakeholders": {
    name: "Стейкхолдер",
    en: "stakeholder",
    def: "Человек или роль, чью работу, риск или право вето затрагивает изменение.",
  },
  "req-quality": {
    name: "INVEST",
    en: "INVEST",
    def: "Гигиена формулировки истории: Independent, Negotiable, Valuable, Estimable, Small, Testable.",
  },
  "req-jira": {
    name: "Jira / Confluence",
    en: "issue tracker",
    def: "Тикет — единица работы с правилом и проверкой. Confluence — конверт, где лежит контекст, не замена тикета.",
  },
  "req-validate": {
    name: "Валидация требования",
    en: "requirements validation",
    def: "Проверка, что правило ещё живое: его можно провалить тестом и за него кто-то отвечает.",
  },
  "req-lifecycle": {
    name: "Change Request",
    en: "change request",
    def: "CR — формальное изменение уже согласованного требования. Комментарий в чате CR не заменяет.",
  },
  "req-test-analysis": {
    name: "Тест-анализ",
    en: "test analysis",
    def: "Разложение Acceptance Criteria в проверяемые кейсы QA: позитив, повтор, отказ, нет данных.",
  },
  "req-estimate": {
    name: "T-shirt sizing",
    en: "t-shirt sizing",
    def: "Грубая оценка объёма S / M / L по дырам в правиле, а не «на глаз сколько дней».",
  },
  "req-gost-34602": {
    name: "ГОСТ 34.602",
    en: "GOST 34.602",
    def: "Российский стандарт содержания технического задания на АСУ: оглавление конверта, не метод выяснить боль.",
  },
  "rest-http": {
    name: "HTTP",
    en: "HTTP",
    name2: "REST",
    en2: "REST",
    def: "HTTP — протокол запрос/ответ: глагол, адрес, код. REST — стиль: ресурсы (кошелёк, платёж), а не процедура «сделатьВсё».",
  },
  "rest-codes": {
    name: "HTTP status code",
    en: "HTTP status code",
    def: "Код ответа: 2xx успех, 4xx ошибка клиента, 5xx сбой сервера. Клиент смотрит код, не прозу в теле.",
  },
  "rest-resource": {
    name: "Ресурс",
    en: "resource",
    def: "Адрес сущности в REST: /wallets/{id}, /holds/{id} — существительное, не глагол /doTransfer.",
  },
  "rest-idem": {
    name: "Идемпотентность",
    en: "idempotency",
    def: "Повтор того же запроса с тем же ключом не создаёт второй эффект: вторая проводка, вторая заявка.",
  },
  "rest-version": {
    name: "Версионирование API",
    en: "API versioning",
    def: "Сосуществование контрактов, когда ломающее изменение нельзя отдать всем клиентам сразу.",
  },
  "rest-errors": {
    name: "Error body",
    en: "error payload",
    def: "Машиночитаемое тело ошибки: код, поле, что показать человеку — не HTML-страница «упс».",
  },
  "rest-explorer": {
    name: "API explorer",
    en: "API explorer",
    def: "Консоль живых запросов к учебному банку: метод, заголовки, тело, ответ.",
  },
  "int-idem": {
    name: "Идемпотентность",
    en: "idempotency",
    def: "Повтор входящего или исходящего сообщения с тем же ключом не создаёт второй факт.",
  },
  "int-task": {
    name: "Постановка",
    en: "development brief",
    def: "Текст, по которому разработчик делает работу, а QA может сказать «не прошло»: need, правило, данные, ошибки, проверка.",
  },
  "int-sync": {
    name: "Синхронный вызов",
    en: "synchronous",
    name2: "Асинхронный",
    en2: "asynchronous",
    def: "Синхронно — вызывающий ждёт ответ в том же разговоре. Асинхронно — кладём факт и узнаём исход позже.",
  },
  "int-webhook": {
    name: "Webhook",
    en: "webhook",
    name2: "Polling",
    en2: "polling",
    def: "Webhook — сосед сам присылает факт на ваш URL. Polling — вы периодически спрашиваете «ну что?».",
  },
  "int-timeout": {
    name: "Timeout",
    en: "timeout",
    name2: "UNKNOWN",
    en2: "unknown",
    def: "Таймаут — ответа нет вовремя. Это не успех и не отказ, а третье состояние: неизвестно.",
  },
  "int-map": {
    name: "Маппинг",
    en: "field mapping",
    name2: "DLQ",
    en2: "dead letter queue",
    def: "Маппинг — как поля одного сообщения становятся полями другого. DLQ — очередь ядовитых сообщений, которые нельзя молча проглотить.",
  },
  "int-queue": {
    name: "Очередь сообщений",
    en: "message queue",
    def: "Брокер (Kafka, RabbitMQ) хранит факты, пока потребитель не обработает. Очередь не отменяет ключ идемпотентности.",
  },
  "int-soap": {
    name: "SOAP",
    en: "SOAP",
    name2: "gRPC",
    en2: "gRPC",
    def: "SOAP — XML-конверт и контракт WSDL. gRPC — бинарный RPC. Конверт не отменяет правило на повтор.",
  },
  "int-oauth": {
    name: "OAuth 2.0",
    en: "OAuth 2.0",
    name2: "JWT",
    en2: "JSON Web Token",
    def: "OAuth — делегирование доступа без пароля в каждой системе. JWT — подписанный токен с утверждениями о том, кто вы.",
  },
  "db-sql": {
    name: "SQL",
    en: "SQL",
    def: "Язык запросов к таблицам: SELECT читает факты. База — строки сущностей, не «одна куча payments».",
  },
  "db-er": {
    name: "ER-модель",
    en: "entity-relationship",
    def: "Сущности и связи данных: кошелёк, холд, проводка — факты, не методы класса.",
  },
  "db-keys": {
    name: "Первичный ключ",
    en: "primary key",
    name2: "UNIQUE",
    en2: "unique constraint",
    def: "PK однозначно называет строку. UNIQUE запрещает дубль там, где бизнес сказал «дважды нельзя».",
  },
  "db-join": {
    name: "JOIN",
    en: "join",
    def: "Склейка таблиц по ключу: холд к кошельку по wallet_id, не «все строки ко всем».",
  },
  "db-m2m": {
    name: "Many-to-many",
    en: "many-to-many",
    def: "Связь «многие ко многим» через связующую таблицу, а не список id в одной ячейке.",
  },
  "db-index": {
    name: "Индекс",
    en: "index",
    def: "Структура, которая ускоряет поиск по полям и может запретить дубль (unique index).",
  },
  "db-json": {
    name: "JSON в БД",
    en: "JSONB",
    def: "Документ в колонке: удобно для хвоста полей, опасно если так прячут ключ или сумму платежа.",
  },
  "db-layers": {
    name: "Слои данных",
    en: "data layers",
    def: "Источник правды (журнал), операционный слой (холд), витрина (экран) — разные таблицы, разные требования.",
  },
  "db-window": {
    name: "Оконная функция",
    en: "window function",
    def: "ROW_NUMBER / RANK считают по строкам, не схлопывая их, в отличие от GROUP BY.",
  },
  "db-cte": {
    name: "CTE",
    en: "common table expression",
    def: "WITH … AS — именованный подзапрос. Читаемость, не матрёшка SELECT в SELECT.",
  },
  "db-migrate": {
    name: "Миграция схемы",
    en: "schema migration",
    def: "Версионированное изменение таблиц: добавить колонку, заполнить, ужесточить NOT NULL. Это требование, не «поправим в проде».",
  },
  "db-dwh": {
    name: "DWH",
    en: "data warehouse",
    name2: "ETL",
    en2: "extract-transform-load",
    def: "Хранилище для отчётов. Зерно (grain) — что означает одна строка витрины. ETL тащит факты из операционки.",
  },
  "arch-bpmn": {
    name: "BPMN",
    en: "BPMN",
    name2: "As-is",
    en2: "as-is",
    def: "Нотация схем процессов. As-is — как процесс идёт сейчас, включая обходы. To-be рисуют после.",
  },
  "arch-hold": {
    name: "Hold",
    en: "authorization hold",
    name2: "Ledger",
    en2: "ledger",
    def: "Hold — бронь суммы: в книге ещё не списано, потратить нельзя. Ledger — журнал проводок debit/credit.",
  },
  "arch-bpmn-mistakes": {
    name: "BPMN",
    en: "BPMN anti-patterns",
    def: "Частые браки схемы: нет дорожки роли, нет события ошибки, счастливый путь без развилки.",
  },
  "arch-uml": {
    name: "UML",
    en: "UML",
    def: "Семейство диаграмм. Для аналитика живые: состояния, последовательность, активность — не «павлин из стрелок».",
  },
  "arch-seq": {
    name: "Sequence diagram",
    en: "sequence diagram",
    def: "UML взаимодействий: кто кого вызывает во времени, где таймаут, где повтор.",
  },
  "arch-c4": {
    name: "C4",
    en: "C4 model",
    def: "Четыре уровня карты системы: Context, Container, Component, Code. Аналитик живёт на 1–2.",
  },
  "arch-journal": {
    name: "Журнал проводок",
    en: "double-entry ledger",
    def: "Каждая операция — две ноги: дебет и кредит одной суммы. Сходимость книги ≠ отсутствие дубля.",
  },
  "arch-p2p": {
    name: "P2P",
    en: "peer-to-peer transfer",
    def: "Перевод между кошельками: две ноги журнала. Без ключа попытки повтор делает четыре ноги.",
  },
  "arch-iban": {
    name: "IBAN",
    en: "IBAN",
    def: "Международный номер счёта. Перевод «к ним» — не внутренний P2P: другой контур, другой журнал.",
  },
  "arch-styles": {
    name: "Стиль архитектуры",
    en: "architecture style",
    def: "Монолит, SOA, микросервисы, EDA — где живёт факт и где рвётся шов. Стиль не цель, а ответ на шов.",
  },
  "arch-eip": {
    name: "EIP",
    en: "enterprise integration patterns",
    def: "Выкройки интеграции: Message, Translator, Router, Dead Letter. Имена паттернов, не «сделаем шину».",
  },
  "arch-saga": {
    name: "Saga",
    en: "saga",
    name2: "Outbox",
    en2: "transactional outbox",
    def: "Сага — длинная операция с компенсациями, если шаг не прошёл. Outbox — письмо соседу пишется в одной транзакции с фактом.",
  },
  "arch-eventstorm": {
    name: "Event Storming",
    en: "event storming",
    def: "Мастерская домена: факты на ленте времени, команды, границы контекста — до нарезки сервисов.",
  },
  "arch-arc42": {
    name: "arc42",
    en: "arc42",
    name2: "ADR",
    en2: "architecture decision record",
    def: "Шаблон описания архитектуры. ADR — короткая запись решения: контекст, выбор, последствия.",
  },
  "api-openapi": {
    name: "OpenAPI",
    en: "OpenAPI Specification",
    def: "Машиночитаемый контракт HTTP API: пути, схемы, коды. Артефакт, который можно провалить, а не скрин из Postman.",
  },
  "api-postman": {
    name: "Postman collection",
    en: "Postman collection",
    def: "Пачка запросов с проверками. Живой контракт, если тесты падают; вики со скрином — нет.",
  },
  "api-asyncapi": {
    name: "AsyncAPI",
    en: "AsyncAPI",
    def: "Контракт событий и топиков: какой канал, какой payload, кто публикует. OpenAPI для асинхронности.",
  },
  "api-graphql": {
    name: "GraphQL",
    en: "GraphQL",
    def: "Клиент описывает форму ответа одним запросом. Деньги и журнал всё равно требуют тот же ключ, что и REST.",
  },
  "api-schema": {
    name: "JSON Schema",
    en: "JSON Schema",
    name2: "XSD",
    en2: "XML Schema",
    def: "Схема полей и типов сообщения. Забор на входе: лишнее отсечь, обязательное потребовать.",
  },
  "api-pagination": {
    name: "Пагинация",
    en: "pagination",
    def: "Нарезка списка: offset/limit или курсор. На живом журнале offset съезжает, курсор держит место.",
  },
  "proc-bpmn-collab": {
    name: "BPMN collaboration",
    en: "BPMN 2.0",
    def: "Несколько дорожек и обмен сообщениями: касса, ядро, шлюз. Событие, компенсация, граница ошибки.",
  },
  "proc-uml-hold": {
    name: "State machine",
    en: "state diagram",
    name2: "Activity",
    en2: "activity diagram",
    def: "Состояния холда (OPEN → CAPTURED / VOID) и активности шагов. Статус — конечный автомат, не 15 подписей.",
  },
  "proc-figma": {
    name: "Figma",
    en: "UI specification",
    def: "Макет экрана. Дыры передачи: что если спиннер, повтор тапа, пустой ответ — в макете часто нет.",
  },
  "proc-mobile-web": {
    name: "Канал ввода",
    en: "channel",
    def: "Мобильный и веб — разные вводы одного правила: двойной тап, обрыв сети, нет hover.",
  },
  "nfr-slo": {
    name: "SLO",
    en: "service level objective",
    name2: "SLI",
    en2: "service level indicator",
    def: "SLI — что мерим (доля 200 за 300 мс). SLO — цель. Error budget — сколько можно нарушать, пока не стоп-релиз.",
  },
  "nfr-security": {
    name: "STRIDE",
    en: "STRIDE",
    name2: "PII",
    en2: "personally identifiable information",
    def: "Модель угроз (подмена, утечка, отказ…). PII — данные, по которым узнают человека. Это NFR, не «потом шифрование».",
  },
  "nfr-pci-log": {
    name: "PCI DSS",
    en: "PCI DSS",
    def: "Правила работы с карточными данными. Номер карты и CVV нельзя писать в лог и журнал зала.",
  },
  "nfr-wcag": {
    name: "WCAG",
    en: "WCAG",
    def: "Критерии доступности интерфейса. Двойное срабатывание с клавиатуры — баг требования, не «дизайн так хотел».",
  },
  "bank-iso20022": {
    name: "ISO 20022",
    en: "ISO 20022",
    name2: "SWIFT",
    en2: "SWIFT",
    def: "Стандарт платёжных сообщений. SWIFT/SEPA несут чужой конверт; наша книга — наши счета и IBAN.",
  },
  "bank-cp-cnp": {
    name: "Card present",
    en: "CP",
    name2: "CNP / 3-D Secure",
    en2: "card not present",
    def: "CP — карта в руках. CNP — карты нет, другой риск и другая проверка (3DS). «Неизвестно» на ACS — не успех.",
  },
  "bank-aml-kyc": {
    name: "KYC",
    en: "know your customer",
    name2: "AML",
    en2: "anti-money laundering",
    def: "KYC — кто клиент. AML — мониторинг подозрительных операций. Комплаенс имеет вето на «удобную» кнопку.",
  },
  "bank-ledger-deep": {
    name: "План счетов",
    en: "chart of accounts",
    def: "Где живут nostro, холд, комиссия. Аналитик называет счёт, не «поле баланса».",
  },
  "bank-recon": {
    name: "Сверка",
    en: "reconciliation",
    def: "Сопоставить наш журнал с файлом соседа. Расхождение — инцидент, не «накиньте до утра».",
  },
  "car-analyst": {
    name: "Бизнес-аналитик",
    en: "business analyst",
    name2: "Системный аналитик",
    en2: "systems analyst",
    def: "BA выявляет потребности стейкхолдеров и формулирует бизнес-требования. SA переводит их в системные требования: данные, интерфейсы, интеграции и правила обработки.",
  },
  "car-intro": {
    name: "STAR",
    en: "situation-task-action-result",
    def: "Каркас ответа на собеседовании: situation, task, action, result. Для аналитика добавьте требование и способ проверки.",
  },
  "car-ethics": {
    name: "Этика",
    en: "professional ethics",
    def: "Профессиональная ответственность за достоверность данных и формулировок. Нельзя сообщать клиенту неверную сумму и скрывать расхождение в учёте.",
  },
  "car-resume": {
    name: "Резюме",
    en: "CV",
    def: "Портфель: какой контур, какое правило, чем измерили — не список курсов и инструментов.",
  },
  "car-interview": {
    name: "Собеседование SA",
    en: "systems analyst interview",
    def: "Просят ход мысли: боль → правило → проверка. Список BPMN/SQL без задачи — слабый ответ.",
  },
  "car-sd": {
    name: "System design",
    en: "system design interview",
    def: "На собесесе: границы, данные, сбой. Не угадать Kafka, а сказать, где факт и где ключ.",
  },
  "car-portfolio": {
    name: "Портфолио",
    en: "portfolio",
    def: "2–3 разбора с артефактом: as-is, правило, тест. Учебный банк можно показывать как контур, не как прод.",
  },
  "car-cert": {
    name: "Сертификация",
    en: "certification",
    def: "IIBA/IQBBA и подобные — ярлык. На собесесе сильнее живой разбор холда, чем бейдж без кейса.",
  },
  "soft-raci": {
    name: "RACI",
    en: "RACI",
    def: "Responsible, Accountable, Consulted, Informed — кто делает, кто отвечает, кого спросить, кому сказать.",
  },
  "soft-workshop": {
    name: "Воркшоп",
    en: "facilitation",
    def: "Сбор фактов в комнате: цель, тайминг, решение на доске. Не созвон «ну как вам идея».",
  },
};
