const o = (text, good, why) => ({ text, good, why });

/** Labs for the expanded materials catalog. Intern-free where intern-level. */
export const EXTRA_LABS = [
  {
    id: "lab-req-ac",
    gradeId: "intern",
    title: "AC, которые ломают",
    teaser: "Given / When / Then. «Стабильно» — не критерий.",
    minutes: 10,
    xp: 70,
    setting: "Тикет WAL-4412. QA спрашивает: чем провалить.",
    blocks: [
      {
        kind: "spot",
        title: "SA · Then",
        prompt: "Что нельзя класть в AC.",
        lines: [
          { id: "1", text: "Система стабильна", bad: true, why: "Пустой Then." },
          { id: "2", text: "Given тот же payment_id, When второй callback, Then нет второй DR", bad: false, why: "Ломается." },
          { id: "3", text: "Как в макете", bad: true, why: "Нет журнала." },
          { id: "4", text: "409 + existingId на повтор ключа", bad: false, why: "Код." },
        ],
      },
      {
        kind: "scene",
        title: "BA+SA · QA",
        setting: "Скопировали AC про SMS.",
        steps: [
          {
            from: "QA",
            line: "Given про OTP, можно закрывать?",
            options: [
              o("Да, шаблон же общий.", false, "Чужой Given."),
              o("Нет. Given этого pay_4412 и журнала.", true, "Нитка."),
              o("Пусть сами допишут.", false, "Угадайка."),
            ],
          },
        ],
      },
    ],
  },
  {
    id: "lab-req-brd",
    gradeId: "junior",
    title: "Граница волны BRD",
    teaser: "Крыша ценности. Won't: Пересчитать и NPS.",
    minutes: 10,
    xp: 80,
    setting: "PO хочет «заодно как у банка».",
    blocks: [
      {
        kind: "sort",
        title: "SA · Куда класть",
        prompt: "Крыша / Won't / экран.",
        buckets: [
          { id: "roof", title: "BRD крыша" },
          { id: "wont", title: "Won't" },
          { id: "ui", title: "Не BRD" },
        ],
        items: [
          { id: "a", text: "Коллектор верит одной сумме 12 000", bucket: "roof", why: "Ценность." },
          { id: "b", text: "Кнопка Пересчитать", bucket: "wont", why: "Косметика." },
          { id: "c", text: "Дашборд NPS", bucket: "wont", why: "Другая волна." },
          { id: "d", text: "Цвет бейджа CRM", bucket: "ui", why: "Экран." },
          { id: "e", text: "Запрет второй DR на ключ", bucket: "roof", why: "Must." },
        ],
      },
    ],
  },
  {
    id: "lab-req-nfr",
    gradeId: "intern",
    title: "NFR ночи",
    teaser: "Лозунг vs правило. Ключ, UNKNOWN, 403.",
    minutes: 10,
    xp: 70,
    setting: "PO: «чтобы было надёжно и быстро».",
    blocks: [
      {
        kind: "spot",
        title: "SA · Это NFR?",
        prompt: "Лозунг отметьте.",
        lines: [
          { id: "1", text: "Система должна быть быстрой", bad: true, why: "Лозунг." },
          { id: "2", text: "ACS 25с без ответа → UNKNOWN", bad: false, why: "Тест." },
          { id: "3", text: "Ключ 24ч, повтор без второй DR", bad: false, why: "Идемпотентность." },
          { id: "4", text: "Безопасно как у банков", bad: true, why: "Чужое." },
        ],
      },
    ],
  },
  {
    id: "lab-req-trace",
    gradeId: "intern",
    title: "Нитка need→тест",
    teaser: "Пустая клетка — дыра до катки.",
    minutes: 8,
    xp: 70,
    setting: "Четыре тикета. Найдите обрыв.",
    blocks: [
      {
        kind: "match",
        title: "SA · Клетки",
        prompt: "Что к чему.",
        pairs: [
          { left: "Need", right: "Одна сумма в звонке" },
          { left: "История", right: "Кусок спринта коллектора" },
          { left: "AC", right: "Then: нет второй DR" },
          { left: "Тест", right: "Два callback QA" },
        ],
      },
      {
        kind: "spot",
        title: "SA · Обрыв",
        prompt: "Где нитка умерла.",
        lines: [
          { id: "1", text: "QA проверил только 201", bad: true, why: "Журнал не смотрел." },
          { id: "2", text: "COUNT ног = 1 на двух POST", bad: false, why: "Then живой." },
          { id: "3", text: "Закрыли UI-историю, need «закрыт»", bad: true, why: "Книга голая." },
        ],
      },
    ],
  },
  {
    id: "lab-req-jira",
    gradeId: "intern",
    title: "Живой тикет",
    teaser: "Jira — спринт. Вики — схема. Не «см. Confluence».",
    minutes: 8,
    xp: 60,
    setting: "Тикет из трёх слов и PDF на 40 страниц.",
    blocks: [
      {
        kind: "spot",
        title: "SA · Брак трекера",
        prompt: "Что не строится.",
        lines: [
          { id: "1", text: "См. Confluence", bad: true, why: "Нет Then." },
          { id: "2", text: "Заголовок: повтор id не создаёт списание", bad: false, why: "Правило." },
          { id: "3", text: "Описание: только Figma", bad: true, why: "Макет ≠ постановка." },
          { id: "4", text: "Won't: Пересчитать", bad: false, why: "Граница." },
        ],
      },
    ],
  },
  {
    id: "lab-sql-join",
    gradeId: "intern",
    title: "JOIN без декарта",
    teaser: "ON ключа. LEFT для холда без ног.",
    minutes: 10,
    xp: 70,
    setting: "Выгрузка раздулась. PO запрещает SQL.",
    blocks: [
      {
        kind: "sort",
        title: "SA · Куда класть",
        prompt: "Ключ / фильтр / брак.",
        buckets: [
          { id: "on", title: "ON / ключ" },
          { id: "wh", title: "WHERE/HAVING" },
          { id: "no", title: "Брак" },
        ],
        items: [
          { id: "a", text: "ON wallet_id", bucket: "on", why: "Склейка." },
          { id: "b", text: "HAVING COUNT(*) > 1", bucket: "wh", why: "Дубли." },
          { id: "c", text: "JOIN без ON", bucket: "no", why: "Декарт." },
          { id: "d", text: "ORDER BY LIMIT 1 как правда", bucket: "no", why: "Дубль." },
          { id: "e", text: "WHERE status = OPEN", bucket: "wh", why: "Строки." },
        ],
      },
    ],
  },
  {
    id: "lab-er-class",
    gradeId: "intern",
    title: "ER vs класс",
    teaser: "Холд — таблица. Не метод Wallet.hold().",
    minutes: 8,
    xp: 70,
    setting: "Dev закрыл тикет методом. В базе холда нет.",
    blocks: [
      {
        kind: "spot",
        title: "SA · Что сущность",
        prompt: "Таблица или метод.",
        lines: [
          { id: "1", text: "Wallet.hold() закрыл тикет, таблицы holds нет", bad: true, why: "Нет факта." },
          { id: "2", text: "holds: id, wallet_id, status OPEN", bad: false, why: "ER." },
          { id: "3", text: "Одно поле balance вместо трёх чисел", bad: true, why: "Витрина." },
          { id: "4", text: "client 1—* wallet", bad: false, why: "Связь." },
        ],
      },
    ],
  },
  {
    id: "lab-sql-m2m",
    gradeId: "intern",
    title: "Многие-ко-многим",
    teaser: "Связующая таблица. Не CSV «admin,ops».",
    minutes: 8,
    xp: 70,
    setting: "Фильтр ночи LIKE '%ops%' ловит ops_delta.",
    blocks: [
      {
        kind: "match",
        title: "SA · Кардинальность",
        prompt: "Какая связь.",
        pairs: [
          { left: "Кошелёк — холды", right: "1 — *" },
          { left: "Клиент — роли", right: "* — * связующая" },
          { left: "CSV в ячейке", right: "Брак фильтра" },
        ],
      },
    ],
  },
  {
    id: "lab-sql-index",
    gradeId: "junior",
    title: "Индекс ночи",
    teaser: "Запрос смены. Unique ≠ «везде».",
    minutes: 8,
    xp: 80,
    setting: "Job OPEN holds не уложился в SLA.",
    blocks: [
      {
        kind: "spot",
        title: "SA · Постановка DBA",
        prompt: "Что нельзя.",
        lines: [
          { id: "1", text: "Добавь индекс везде", bad: true, why: "Запись встанет." },
          { id: "2", text: "WHERE wallet_id, status OPEN — вот запрос", bad: false, why: "NFR." },
          { id: "3", text: "UNIQUE ключа попытки", bad: false, why: "Запрет дубля." },
          { id: "4", text: "Индекс вместо AC на повтор", bad: true, why: "Скорость ≠ правило API." },
        ],
      },
    ],
  },
  {
    id: "lab-sql-json",
    gradeId: "intern",
    title: "JSON и колонки",
    teaser: "Сумма в колонке. Callback — след.",
    minutes: 8,
    xp: 70,
    setting: "Сверку просят парсить JSON в Excel.",
    blocks: [
      {
        kind: "sort",
        title: "SA · Куда поле",
        prompt: "Колонка / след / нельзя.",
        buckets: [
          { id: "col", title: "Колонка" },
          { id: "js", title: "JSON-след" },
          { id: "no", title: "Нельзя" },
        ],
        items: [
          { id: "a", text: "amount, currency, payment_id", bucket: "col", why: "Факт." },
          { id: "b", text: "Сырой callback шлюза", bucket: "js", why: "Спор." },
          { id: "c", text: "Ledger только в JSON", bucket: "no", why: "Книга." },
          { id: "d", text: "UNIQUE на колонке ключа", bucket: "col", why: "Дубль." },
        ],
      },
    ],
  },
  {
    id: "lab-rest-codes",
    gradeId: "intern",
    title: "Коды: ретраить?",
    teaser: "409 стоп. 5xx — тот же ключ. 200+false — ложь.",
    minutes: 10,
    xp: 70,
    setting: "Интегратор крутит всё, что не 201.",
    blocks: [
      {
        kind: "sort",
        title: "SA · Сигнал",
        prompt: "Повтор / стоп / чинить поле.",
        buckets: [
          { id: "retry", title: "Тот же ключ" },
          { id: "stop", title: "Не новый POST" },
          { id: "fix", title: "Поле / доступ" },
        ],
        items: [
          { id: "a", text: "5xx / timeout", bucket: "retry", why: "UNKNOWN." },
          { id: "b", text: "409 existingId", bucket: "stop", why: "Дубль." },
          { id: "c", text: "422 amount", bucket: "fix", why: "Валидация." },
          { id: "d", text: "403 intern запись", bucket: "fix", why: "Тариф." },
          { id: "e", text: "200 + success false", bucket: "stop", why: "Брак контракта." },
        ],
      },
    ],
  },
  {
    id: "lab-rest-resource",
    gradeId: "intern",
    title: "Имена ресурсов",
    teaser: "Не /doTransferNow.",
    minutes: 8,
    xp: 60,
    setting: "Фронт принёс глаголы в URL.",
    blocks: [
      {
        kind: "spot",
        title: "SA · URL",
        prompt: "Брак отметьте.",
        lines: [
          { id: "1", text: "POST /doTransferNow", bad: true, why: "RPC." },
          { id: "2", text: "POST /transfers + ключ", bad: false, why: "Ресурс." },
          { id: "3", text: "PATCH /wallets/{id}/balance", bad: true, why: "Витрина." },
          { id: "4", text: "GET /holds?status=OPEN", bad: false, why: "Чтение." },
        ],
      },
    ],
  },
  {
    id: "lab-rest-version",
    gradeId: "junior",
    title: "Ломаем v1?",
    teaser: "Единицы amount молча — ночь кассы.",
    minutes: 8,
    xp: 80,
    setting: "Dev хочет тийины в том же /v1.",
    blocks: [
      {
        kind: "scene",
        title: "SA · Соседняя касса",
        setting: "Клиент на /v1 с UZS.",
        steps: [
          {
            from: "Dev",
            line: "Поменяем amount на тийины, они обновятся.",
            options: [
              o("Ок, один спринт.", false, "Ломаем молча."),
              o("Это слом смысла. v2 или адаптер, дата смерти v1.", true, "Контракт."),
              o("Пусть касса парсит оба.", false, "Зоопарк без договора."),
            ],
          },
        ],
      },
    ],
  },
  {
    id: "lab-webhook",
    gradeId: "intern",
    title: "Callback и опрос",
    teaser: "Webhook стучится. Polling — страховка UNKNOWN. Не POST оплаты.",
    minutes: 10,
    xp: 70,
    setting: "Шлюз потерял POST. Касса орёт.",
    blocks: [
      {
        kind: "match",
        title: "SA · Кто инициирует",
        prompt: "Путь факта.",
        pairs: [
          { left: "Webhook", right: "Шлюз → наш URL, повтор 409" },
          { left: "Polling", right: "GET статуса, не новый POST" },
          { left: "Касса ждёт", right: "Синхрон authorize + UNKNOWN" },
        ],
      },
      {
        kind: "spot",
        title: "SA · Брак",
        prompt: "Что нельзя.",
        lines: [
          { id: "1", text: "Опрос POST /transfers каждые 50 мс", bad: true, why: "Эффект." },
          { id: "2", text: "Второй callback с тем же rrn → 409", bad: false, why: "Ключ." },
          { id: "3", text: "Только webhook, план на тишину нет", bad: true, why: "UNKNOWN." },
        ],
      },
    ],
  },
  {
    id: "lab-queue",
    gradeId: "junior",
    title: "Kafka vs Rabbit",
    teaser: "Лог vs задача. Ключ handler. Не склад вложений.",
    minutes: 10,
    xp: 90,
    setting: "Предлагают Kafka, потому что вакансия.",
    blocks: [
      {
        kind: "sort",
        title: "SA · Инструмент",
        prompt: "Лог / задача / общее.",
        buckets: [
          { id: "log", title: "Ближе к логу" },
          { id: "job", title: "Ближе к задаче" },
          { id: "both", title: "Обязательно SA" },
        ],
        items: [
          { id: "a", text: "Несколько читателей одного потока", bucket: "log", why: "Kafka-стиль." },
          { id: "b", text: "Сделай один раз, ack", bucket: "job", why: "Rabbit-стиль." },
          { id: "c", text: "Идемпотентный handler + DLQ", bucket: "both", why: "Контракт." },
          { id: "d", text: "Гигантское письмо в теле", bucket: "job", why: "Опасность брокера — всё равно брак размера." },
        ],
      },
    ],
  },
  {
    id: "lab-soap",
    gradeId: "intern",
    title: "Три конверта",
    teaser: "XML, JSON, protobuf. Ключ общий. Need один.",
    minutes: 8,
    xp: 70,
    setting: "Сосед WSDL. Зал REST. PO: «переведём всё».",
    blocks: [
      {
        kind: "spot",
        title: "SA · Шов",
        prompt: "Что брак.",
        lines: [
          { id: "1", text: "SOAP мёртв, пусть сосед умрёт", bad: true, why: "Шов." },
          { id: "2", text: "Их MsgId = наш Idempotency-Key", bad: false, why: "Маппинг." },
          { id: "3", text: "gRPC наружу кассе без клиента", bad: true, why: "Потребитель." },
          { id: "4", text: "WSDL есть, повтора нет", bad: true, why: "Конверт ≠ AC." },
        ],
      },
    ],
  },
  {
    id: "lab-oauth",
    gradeId: "intern",
    title: "Кто ты и что можно",
    teaser: "401/403. Токен ≠ ключ перевода. Intern может получить 403 на запись.",
    minutes: 8,
    xp: 60,
    setting: "Dev кладёт JWT в Idempotency-Key.",
    blocks: [
      {
        kind: "match",
        title: "SA · Слои",
        prompt: "Не склеить.",
        pairs: [
          { left: "401", right: "Не представился" },
          { left: "403", right: "Нельзя (тариф intern)" },
          { left: "Idempotency-Key", right: "Попытка эффекта, не токен" },
        ],
      },
    ],
  },
  {
    id: "lab-mapping-dlq",
    gradeId: "junior",
    title: "Маппинг и яд",
    teaser: "Единицы. Мастер. DLQ не помойка без алерта.",
    minutes: 10,
    xp: 90,
    setting: "Amount то UZS то тийины. Неизвестный IBAN глотали.",
    blocks: [
      {
        kind: "spot",
        title: "SA · Таблица",
        prompt: "Брак.",
        lines: [
          { id: "1", text: "Единицы «очевидны»", bad: true, why: "Порядок." },
          { id: "2", text: "Неизвестный IBAN → suspense + DLQ", bad: false, why: "Яд." },
          { id: "3", text: "Партнёр всегда master книги", bad: true, why: "KYC." },
          { id: "4", text: "DLQ без хозяина и алерта", bad: true, why: "Копится." },
        ],
      },
    ],
  },
  {
    id: "lab-uml-seq",
    gradeId: "intern",
    title: "Sequence кассы",
    teaser: "Стрелка повтора и таймаута. Журнал на схеме.",
    minutes: 8,
    xp: 70,
    setting: "Нарисовали счастливый путь. Ночь другая.",
    blocks: [
      {
        kind: "order",
        title: "SA · Сообщения",
        prompt: "Порядок.",
        items: [
          { id: "1", text: "POST authorize + ключ", pos: 1 },
          { id: "2", text: "ACS думает / таймаут UNKNOWN", pos: 2 },
          { id: "3", text: "Callback (возможен повтор 409)", pos: 3 },
          { id: "4", text: "GET статус если тишина", pos: 4 },
        ],
      },
    ],
  },
  {
    id: "lab-iban",
    gradeId: "intern",
    title: "Входящий IBAN",
    teaser: "Nostro. Неясные — suspense. Не накинуть.",
    minutes: 8,
    xp: 70,
    setting: "Файл партнёра. Клиента нет. Главбух: накиньте.",
    blocks: [
      {
        kind: "spot",
        title: "SA · Ноги",
        prompt: "Что нельзя.",
        lines: [
          { id: "1", text: "Накиньте гостю", bad: true, why: "AML." },
          { id: "2", text: "Nostro ↑, клиент известен → пассив клиента", bad: false, why: "Контур." },
          { id: "3", text: "Неизвестен → suspense + тикет", bad: false, why: "Разбор." },
          { id: "4", text: "Файл master KYC", bad: true, why: "Не книга личности." },
        ],
      },
    ],
  },
  {
    id: "lab-p2p",
    gradeId: "intern",
    title: "P2P Анна → Борис",
    teaser: "Две ноги. Учебный дубль без ключа.",
    minutes: 8,
    xp: 70,
    setting: "Два POST 5000. Trial сошёлся. Анна −10000.",
    blocks: [
      {
        kind: "match",
        title: "SA · Ноги",
        prompt: "Пассив.",
        pairs: [
          { left: "Анна отдала", right: "DR пассива" },
          { left: "Борис получил", right: "CR пассива" },
          { left: "Второй POST без ключа", right: "Учебный баг, вторая пара" },
        ],
      },
    ],
  },
  {
    id: "lab-bpmn-mistakes",
    gradeId: "junior",
    title: "Брак BPMN",
    teaser: "Павлин, актёр «система», auth = проводка.",
    minutes: 8,
    xp: 80,
    setting: "Красивая схема. Смена не узнаёт ночь.",
    blocks: [
      {
        kind: "spot",
        title: "SA · Схема",
        prompt: "Что врёт.",
        lines: [
          { id: "1", text: "40 блоков, никто не читает", bad: true, why: "Павлин." },
          { id: "2", text: "Excel как шаг as-is", bad: false, why: "Правда." },
          { id: "3", text: "Актёр «система» на всех дорожках", bad: true, why: "Нет дежурного." },
          { id: "4", text: "Auth подписан как проводка", bad: true, why: "Холд." },
        ],
      },
    ],
  },
];
