package petdb

func ExplorerCatalog() []map[string]any {
	d := func(group, title, when, method, path, auth string, body any, headers map[string]string, db, errors, bug string) map[string]any {
		return map[string]any{
			"group": group, "title": title, "when": when, "method": method, "path": path,
			"auth": auth, "example": body, "headers": headers, "db": db, "errors": errors, "bug": bug,
			"write": method != "GET",
		}
	}
	h := map[string]string{"Content-Type": "application/json"}
	idem := map[string]string{"Content-Type": "application/json", "Idempotency-Key": "p2p-desk-001"}
	sid := "Сессия cookie malo_sid. GET доступен Intern. POST, PUT, PATCH — PRO или 3-дневный триал."
	return []map[string]any{
		d("Счета", "План счетов и пробный баланс",
			"Сверка: какие счета есть, какой ledger и available, сходится ли книга по валюте.",
			"GET", "/api/v1/accounts", sid, nil, nil,
			"Читает accounts и открытые holds. Пробный баланс считает по проводкам журнала, не по полю balance.",
			"404 на списке не бывает.",
			"В сиде учебная дыра REFUND_HOLE даёт diff ≠ 0. Сходимость книги и отсутствие дубля перевода — разные проверки."),
		d("Счета", "Выписка счёта",
			"Клиент оспаривает движение. Нужна лента проводок с balanceAfter.",
			"GET", "/api/v1/accounts/acc_anna/statement", sid, nil, nil,
			"Проводки ledger_legs по accountId, сортировка по at.",
			"404 — счёт не найден.", ""),
		d("Счета", "Кошельки (витрина)",
			"Что видит клиент в приложении. available = ledger − сумма OPEN holds.",
			"GET", "/api/v1/wallets", sid, nil, nil,
			"Витрина wallets + accounts + holds + kyc. Журнал не пишет.",
			"", "Не путать available с ledger. Холд уменьшает available, проводки ещё нет."),
		d("Счета", "Один кошелёк",
			"Карточка одного клиента на разборе тикета.",
			"GET", "/api/v1/wallets/wal_anna", sid, nil, nil,
			"Та же витрина, один id.", "404 WALLET", ""),
		d("Счета", "Клиенты ядра",
			"Реестр розницы учебного банка.",
			"GET", "/api/v1/customers", sid, nil, nil,
			"Таблица customers из сида.", "", ""),
		d("Счета", "Состояние ядра",
			"Снимок для разбора: контракт, счета, журналы, холды, тикеты, пробный баланс.",
			"GET", "/api/v1/state", sid, nil, nil,
			"Полный snapshot учебного банка.", "", "Поле missions.reproducedDouble отмечает учебный двойной P2P."),
		d("Холды", "Список холдов",
			"Касса вернула SUCCESS, в журнале пусто. Проверьте OPEN hold.",
			"GET", "/api/v1/holds", sid, nil, nil,
			"Таблица holds. Статус OPEN уменьшает available, проводок нет.",
			"", "В сиде у Дины холд 200 000 при ledger 80 000 — учебный инцидент."),
		d("Холды", "Один холд",
			"Разбор конкретного authorize: чей счёт, сколько зарезервировано, связан ли платёж.",
			"GET", "/api/v1/holds/hld_dina_over", sid, nil, nil,
			"holds по id.", "404", ""),
		d("Холды", "Авторизация карты (auth)",
			"Терминал запрашивает резерв. Если holdThenCapture включён, пишется холд, не журнал.",
			"POST", "/api/v1/cards/authorize", sid,
			map[string]any{"walletId": "wal_boris", "cardId": "crd_boris", "amount": 12000, "currency": "UZS"},
			map[string]string{"Content-Type": "application/json", "X-ACS-Timeout": "0"},
			"INSERT holds OPEN, payments AUTHORIZED, card_auths. Журнала нет до capture.",
			"409 INSUFFICIENT, CARD_BLOCKED, CARD_WALLET. 404 WALLET/CARD.",
			"Контракт ACS timeout: по умолчанию SUCCESS и учебная ложная проводка CARD_FALSE_SUCCESS."),
		d("Холды", "Capture платежа",
			"После auth эквайер запрашивает списание. Холд закрывается, в журнале появляются DR клиента и CR мерчанта.",
			"POST", "/api/v1/payments/pay_cafe_auth_1/capture", sid,
			map[string]any{"amount": 18000}, h,
			"Журнал CARD_CAPTURE, hold → CAPTURED, payment CAPTURED. Комиссия feeOnCaptureBps — отдельный CR на acc_fee.",
			"409 STATE, если платёж не AUTHORIZED. 404.",
			"Частичный capture только при allowPartialCapture. Иначе касса на 4 000 может списать 12 000."),
		d("Холды", "Отмена auth (void)",
			"Клиент отказался до capture. Холд снять, журнала быть не должно.",
			"POST", "/api/v1/payments/pay_cafe_auth_1/cancel", sid, map[string]any{}, h,
			"hold RELEASED, payment CANCELED. Проводок нет.",
			"409, если уже CAPTURED — тогда refund, не void.", ""),
		d("Журнал", "Журналы",
			"Книга операций: kind, debit/credit, balanced, four_eyes.",
			"GET", "/api/v1/ledger/journals", sid, nil, nil,
			"journals и агрегат trial.", "", "В сиде ищите REFUND_HOLE и nightShift."),
		d("Журнал", "Проводки книги",
			"Детализация DR/CR. Фильтр ?accountId=acc_anna.",
			"GET", "/api/v1/ledger", sid, nil, nil,
			"ledger_legs.", "", ""),
		d("Журнал", "Пробный баланс",
			"Контроль: сумма дебетов равна сумме кредитов по валюте.",
			"GET", "/api/v1/ledger/trial-balance", sid, nil, nil,
			"Сумма живых проводок. diff — расхождение книги.", "", "Сид содержит одностороннюю REFUND_HOLE."),
		d("Журнал", "T-счёт",
			"На разборе: слева DR, справа CR по одному счёту.",
			"GET", "/api/v1/ledger/t-accounts/acc_anna", sid, nil, nil,
			"Проводки счёта.", "404", ""),
		d("Журнал", "Сторно журнала",
			"Ошибочная проводка. Сторно — обратные записи, не DELETE из журнала.",
			"POST", "/api/v1/ledger/journals/{id}/reverse", sid, map[string]any{}, h,
			"Новый журнал *_REV, original.reversedBy.",
			"409, если уже сторнирован или нет проводок.", ""),
		d("P2P", "Перевод кошелёк → кошелёк",
			"Клиент в приложении: Анна платит Борису. Это внутренний перевод пассивов, не IBAN.",
			"POST", "/api/v1/transfers", sid,
			map[string]any{"fromWalletId": "wal_anna", "toWalletId": "wal_boris", "amount": 5000, "currency": "UZS"},
			idem,
			"Журнал P2P: DR отправитель, CR получатель. Строка transfers. Ключ — заголовок Idempotency-Key.",
			"409 INSUFFICIENT, LIMIT, CCY. 404 WALLET. 400 без ключа, если контракт его требует.",
			"По умолчанию ключ не обязателен: повтор без Idempotency-Key создаёт вторую проводку. Учебный дефект. В сиде уже есть такие переводы."),
		d("IBAN", "Входящий платёж по IBAN",
			"Корреспондент прислал зачисление. Nostro растёт, клиент кредитуется. Неизвестный IBAN — suspense.",
			"POST", "/api/v1/bank/incoming", sid,
			map[string]any{"iban": "UZ12MALO000000000001", "amount": 25000, "currency": "UZS", "paymentRef": "MT103-TEST"},
			h,
			"DR acc_nostro, CR клиента. Неизвестный IBAN: CR acc_suspense и incoming SUSPENSE, если unknownIbanToSuspense.",
			"404 IBAN, если контракт не кладёт в suspense. 400 без полей.",
			"Сид: in_old — невыясненная 175 000 старше суток."),
		d("IBAN", "Входящие",
			"Реестр зачислений для ночной сверки.",
			"GET", "/api/v1/bank/incoming", sid, nil, nil, "Таблица incoming.", "", ""),
		d("IBAN", "Невыясненные",
			"Очередь денег с неизвестным IBAN. SLA старения — отдельное требование.",
			"GET", "/api/v1/bank/suspense", sid, nil, nil, "Таблица suspense.", "", ""),
		d("IBAN", "Разнести suspense",
			"Нашли правильный IBAN клиента. DR suspense, CR клиент.",
			"POST", "/api/v1/bank/suspense/in_old/allocate", sid,
			map[string]any{"iban": "UZ12MALO000000000001"}, h,
			"Журнал SUSPENSE_ALLOC.", "409, если уже разнесён. 404 IBAN.", ""),
		d("IBAN", "Исходящий перевод",
			"Клиент платит в другой банк. Пока нет ack — холд, не списание.",
			"POST", "/api/v1/bank/outgoing", sid,
			map[string]any{"fromWalletId": "wal_anna", "iban": "UZ12ORNT0000009999", "amount": 7000, "purpose": "RENT"},
			h,
			"holds OPEN и outgoing PENDING_BANK. Журнала нет.",
			"409 INSUFFICIENT.", "Не путать холд исходящего с уже ушедшими деньгами."),
		d("IBAN", "Ack банка по исходящему",
			"Корреспондент ответил posted или rejected.",
			"POST", "/api/v1/bank/outgoing/{id}/ack", sid,
			map[string]any{"result": "posted"}, h,
			"posted: DR клиент CR nostro, hold CAPTURED, MT103. rejected: hold RELEASED, журнала нет.",
			"409 STATE.", ""),
		d("IBAN", "MT103",
			"Документ следствия posted, не master-статус операции.",
			"GET", "/api/v1/bank/outgoing/{id}/mt103", sid, nil, nil,
			"Поле mt103 исходящего.", "409, пока статус не POSTED.", ""),
		d("IBAN", "Исходящие",
			"Очередь PENDING_BANK для операциониста.",
			"GET", "/api/v1/bank/outgoing", sid, nil, nil, "Таблица outgoing.", "", ""),
		d("IBAN", "Зарплатный файл",
			"HR принёс реестр. Trailer должен совпасть с суммой строк, если включён контракт.",
			"POST", "/api/v1/bank/salary", sid,
			map[string]any{"fileName": "salary-sep.csv", "trailerSum": 150000, "rows": []any{
				map[string]any{"iban": "UZ12MALO000000000002", "amount": 150000},
			}}, h,
			"По строке: DR nostro CR клиент, либо REJECTED.",
			"409 DUPLICATE_FILE, 400 TRAILER.", "«Загрузите, завтра поправим» — дыра в книге на размер trailer."),
		d("IBAN", "Реестр зарплат",
			"Ночная смена сверяет, какие файлы уже прошли.",
			"GET", "/api/v1/bank/salary", sid, nil, nil, "Таблица salary.", "", ""),
		d("FX", "Курсы",
			"Казначейство: mid и спред в bps из контракта.",
			"GET", "/api/v1/fx", sid, nil, nil, "fx и contract.fxSpreadBps.", "", ""),
		d("FX", "Конвертация UZS → USD",
			"Клиент покупает валюту. Два журнала: UZS и USD, спред отдельной проводкой.",
			"POST", "/api/v1/fx/convert", sid,
			map[string]any{"fromWalletId": "wal_anna", "toWalletId": "wal_anna_usd", "amountTo": 10}, h,
			"FX_UZS и FX_USD. fx_deals POSTED с cover-журналами.",
			"409 CCY/PAIR/INSUFFICIENT.", "Одна проводка на две валюты запрещена смыслом книги."),
		d("FX", "Сделки FX",
			"Поиск сделок без покрытия: BOOKED без журнала.",
			"GET", "/api/v1/fx/deals", sid, nil, nil,
			"fx_deals. Сид: fx_naked без журнала.", "", "Учебная сделка без cover."),
		d("Карты", "Пластик",
			"Карты клиентов. Блок не даёт auth, если blockedCardCannotAuth.",
			"GET", "/api/v1/cards", sid, nil, nil, "cards/plastic.", "", "crd_elena в BLOCKED."),
		d("Карты", "Выпустить карту",
			"Онбординг: карта к кошельку.",
			"POST", "/api/v1/cards/issue", sid,
			map[string]any{"walletId": "wal_anna", "scheme": "HUMO"}, h,
			"INSERT plastic.", "404 WALLET.", ""),
		d("Карты", "Блок карты",
			"Клиент потерял карту. Auth дальше зависит от контракта.",
			"POST", "/api/v1/cards/crd_boris/block", sid, map[string]any{}, h,
			"plastic.status = BLOCKED.", "404", ""),
		d("Карты", "Auth-журнал кассы",
			"ACS OK / TIMEOUT. Не путать с книгой проводок.",
			"GET", "/api/v1/auths", sid, nil, nil, "card_auths.", "", ""),
		d("Карты", "Платежи",
			"AUTHORIZED / CAPTURED / REFUNDED — разные состояния книги.",
			"GET", "/api/v1/payments", sid, nil, nil, "payments.", "", ""),
		d("Карты", "Один платёж",
			"Карточка платежа: статус, холд, RRN, журнал.",
			"GET", "/api/v1/payments/{id}", sid, nil, nil, "payments.", "404", ""),
		d("Карты", "Refund",
			"Возврат после capture. Должен реверсить мерчанта, иначе дыра в книге.",
			"POST", "/api/v1/payments/{id}/refund", sid, map[string]any{"amount": 1000}, h,
			"Журнал реверса, если refundPostsReversal.",
			"409 STATE.", "Без реверса мерчанта пробный баланс расходится — как REFUND_HOLE в сиде."),
		d("Карты", "Chargeback",
			"Спор по карте. Расход acc_cb.",
			"POST", "/api/v1/payments/{id}/chargeback", sid, map[string]any{}, h,
			"Проводки chargeback.", "409 STATE.", ""),
		d("Карты", "Мерчанты",
			"Cafe / Taxi / Pharma — для SQL «auth vs capture».",
			"GET", "/api/v1/merchants", sid, nil, nil, "merchants.", "", ""),
		d("Карты", "Клиринг T+1",
			"Выплата мерчанту — другой журнал, не касса.",
			"GET", "/api/v1/clearing", sid, nil, nil, "clearing.", "", ""),
		d("Карты", "Сетить клиринг",
			"DR мерчант CR nostro на всю позицию.",
			"POST", "/api/v1/clearing/settle", sid, map[string]any{}, h,
			"CLEARING_SETTLE.", "409 NOTHING, если мерчанту нечего селить.", ""),
		d("Сверка", "Экспорт нашего реестра",
			"RRN и сумма для файла партнёра.",
			"GET", "/api/v1/recon/export", sid, nil, nil, "payments со статусом CAPTURED и далее.", "", ""),
		d("Сверка", "Прогнать файл партнёра",
			"MATCH / MISMATCH / UNKNOWN_RRN / MISSING_IN_FILE.",
			"POST", "/api/v1/recon/ingest", sid,
			map[string]any{"source": "visa", "rows": []any{map[string]any{"rrn": "rrn_pay_cafe_cap_1", "amount": 14000}}}, h,
			"Запуск сверки.", "", "Сверка «примерно, копейки не смотрим» без допуска в контракте — ошибка требования."),
		d("KYC", "Заявки",
			"Анна PENDING: если kycIsMaster, кошелёк не ACTIVE.",
			"GET", "/api/v1/kyc", sid, nil, nil, "kyc.", "", ""),
		d("KYC", "Старт KYC",
			"Новый клиент. Повтор с тем же ключом не создаёт вторую заявку.",
			"POST", "/api/v1/kyc/start", sid, map[string]any{"customer": "dina"}, idem,
			"kyc PENDING.", "400 без customer.", ""),
		d("KYC", "Решение KYC",
			"Комплаенс: APPROVED или REJECTED. Решение фиксируется в API, не в чате.",
			"POST", "/api/v1/kyc/kyc_anna/decide", sid, map[string]any{"status": "APPROVED", "reason": "паспорт ок"}, h,
			"kyc status.", "400 STATUS.", ""),
		d("Контракт", "Прочитать контракт ядра",
			"Флаги, которые включают или выключают учебные дефекты.",
			"GET", "/api/v1/contract", sid, nil, nil, "contract в JSON банка.", "", ""),
		d("Контракт", "Поменять контракт",
			"Включить обязательную идемпотентность P2P и честный ACS timeout.",
			"PATCH", "/api/v1/contract", sid,
			map[string]any{"transferIdempotencyRequired": true, "transferDuplicateHttp": 409, "errorInBody": false, "holdThenCapture": true, "acsTimeoutStatus": "UNKNOWN"},
			h, "Пишет contract, не журнал.", "", "Смена флагов — часть практики, не «починить прод руками»."),
		d("Контракт", "Сбросить учебный банк",
			"Вернуть сид с аномалиями: дубль P2P, FX без покрытия, suspense, дыра журнала.",
			"POST", "/api/v1/reset", sid, map[string]any{}, h,
			"Пересоздаёт JSON и SQL-лабу.", "", ""),
		d("Тикеты", "Очередь линии",
			"Очередь инцидентов учебного банка.",
			"GET", "/api/v1/tickets", sid, nil, nil, "tickets.", "", ""),
		d("Тикеты", "Один тикет",
			"Разбор инцидента: холд, P2P, suspense, FX, ночная смена.",
			"GET", "/api/v1/tickets/tkt_hold", sid, nil, nil, "tickets.", "404", ""),
		d("Тикеты", "Создать тикет",
			"Фиксация инцидента в очереди, не в мессенджере.",
			"POST", "/api/v1/tickets", sid,
			map[string]any{"title": "Повторный capture на кассе", "customer": "boris", "kind": "CARD", "priority": "P1", "body": "RRN неизвестен, холд висит."},
			h, "INSERT tickets.", "400 без title.", ""),
		d("Тикеты", "Комментарий к тикету",
			"Ход разбора: что нашли в SQL и какой AC пишем.",
			"POST", "/api/v1/tickets/tkt_p2p/comment", sid,
			map[string]any{"text": "Два P2P без ключа, готовлю AC на 409.", "status": "OPEN"}, h,
			"tickets.comments.", "400 пустой текст.", ""),
		d("Тикеты", "Аудит вызовов API",
			"Кто вызывал ядро и с каким статусом.",
			"GET", "/api/v1/audit", sid, nil, nil, "audit.", "", ""),
		d("Магазин", "Остатки ShopLine",
			"Соседний контур квеста, не ядро банка.",
			"GET", "/api/v1/shopline/stock", sid, nil, nil, "stock.", "", ""),
		d("Магазин", "Заказ ShopLine",
			"Соседний контур с тем же правилом идемпотентности, что и P2P.",
			"POST", "/api/v1/shopline/orders", sid, map[string]any{"sku": "SKU-100", "qty": 1}, idem,
			"orders, уменьшает qty.", "409 STOCK, 400 без ключа если контракт.", ""),
	}
}
